### ISSUE TITLE
logging error in the QGIS-python console (print)

### ISSUE THREAD

**Issue by dieuska** [OnroerendErfgoed/brdrQ#28]
When executing brdrQ, a logging error is shown in the QGIS python print console:

--- Logging error ---
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 232, in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 435, in executeAlgorithm
    dlg.exec()
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 332, in runAlgorithm
    ok, results = execute(self.algorithm(), parameters, self.context, self.feedback)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 62, in execute
    results, ok = alg.run(parameters, context, feedback)
  File "C:\Users\KarelDieussaert\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\autocorrectborders.py", line 668, in processAlgorithm
    aligner = Aligner(feedback=log_info,
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 158, in __init__
    self.logger.feedback_info("Aligner initialized")
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\logger.py", line 22, in feedback_info
    logging.info(text)
Message: 'Aligner initialized'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 232, in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 435, in executeAlgorithm
    dlg.exec()
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 332, in runAlgorithm
    ok, results = execute(self.algorithm(), parameters, self.context, self.feedback)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 62, in execute
    results, ok = alg.run(parameters, context, feedback)
  File "C:\Users\KarelDieussaert\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\autocorrectborders.py", line 705, in processAlgorithm
    aligner.load_reference_data(
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 1054, in load_reference_data
    ) = loader.load_data()
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\grb.py", line 438, in load_data
    self.aligner.logger.feedback_info(f"GRB downloaded: {self.grb_type}")
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\logger.py", line 22, in feedback_info
    logging.info(text)
Message: 'GRB downloaded: GRBType.ADP'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 232, in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 435, in executeAlgorithm
    dlg.exec()
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 332, in runAlgorithm
    ok, results = execute(self.algorithm(), parameters, self.context, self.feedback)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 62, in execute
    results, ok = alg.run(parameters, context, feedback)
  File "C:\Users\KarelDieussaert\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\autocorrectborders.py", line 705, in processAlgorithm
    aligner.load_reference_data(
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 1055, in load_reference_data
    self._prepare_reference_data()
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 682, in _prepare_reference_data
    self.logger.feedback_info(
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\logger.py", line 22, in feedback_info
    logging.info(text)
Message: 'length of reference_dict: 366'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 232, in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 435, in executeAlgorithm
    dlg.exec()
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 332, in runAlgorithm
    ok, results = execute(self.algorithm(), parameters, self.context, self.feedback)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 62, in execute
    results, ok = alg.run(parameters, context, feedback)
  File "C:\Users\KarelDieussaert\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\autocorrectborders.py", line 717, in processAlgorithm
    process_result = aligner.process_dict_thematic(
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 301, in process_dict_thematic
    self.logger.feedback_info("thematic id to process: " + str(key))
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\logger.py", line 22, in feedback_info
    logging.info(text)
Message: 'thematic id to process: 100'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 232, in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 435, in executeAlgorithm
    dlg.exec()
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 332, in runAlgorithm
    ok, results = execute(self.algorithm(), parameters, self.context, self.feedback)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 62, in execute
    results, ok = alg.run(parameters, context, feedback)
  File "C:\Users\KarelDieussaert\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\autocorrectborders.py", line 717, in processAlgorithm
    process_result = aligner.process_dict_thematic(
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 301, in process_dict_thematic
    self.logger.feedback_info("thematic id to process: " + str(key))
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\logger.py", line 22, in feedback_info
    logging.info(text)
Message: 'thematic id to process: 200'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 232, in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 435, in executeAlgorithm
    dlg.exec()
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 332, in runAlgorithm
    ok, results = execute(self.algorithm(), parameters, self.context, self.feedback)
  File "C:\PROGRA~1/QGIS33~1.1/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 62, in execute
    results, ok = alg.run(parameters, context, feedback)
  File "C:\Users\KarelDieussaert\AppData\Roaming\QGIS\QGIS3\profiles\default\processing\scripts\autocorrectborders.py", line 717, in processAlgorithm
    process_result = aligner.process_dict_thematic(
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\aligner.py", line 301, in process_dict_thematic
    self.logger.feedback_info("thematic id to process: " + str(key))
  File "C:\Users\KarelDieussaert\AppData\Roaming\Python\Python312\site-packages\brdr\logger.py", line 22, in feedback_info
    logging.info(text)
Message: 'thematic id to process: 300'
Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
    ^^^^^^^^^^^^

**Comment by dieuska** [comment]
When adding the QGIS feedback logger to the aligner, ther isn't a problem. When setting this to None this error occurs. To check if brdr handles this correctly when no QGIS-logger is provided.

**Comment by dieuska** [comment]
zie: https://github.com/OnroerendErfgoed/brdrQ/blob/5fd46d81c0529da05783cddfb71797d7e9cff468/autocorrectborders.py#L684-L691

**Comment by dieuska** [comment]
fix was needed in brdr. This fix will be available from version >=0.2.2

**Comment by dieuska** [comment]
we close this here as this is already fixed in brdr
